name: Deploy

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://pminsun:${{ secrets.AUTO_ACTIONS }}@github.com/pminsun/TtorangttorangWeb
          git config user.name "pminsun"
          git config user.email "pminsun309@gmail.com"

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo main

      - name: Clean up
        run: |
          git remote remove forked-repo
